python make3Dplot.py BASO_COUNT
python make3Dplot.py EO_COUNT
python make3Dplot.py HCT
python make3Dplot.py HGB
python make3Dplot.py LYMPH_COUNT
python make3Dplot.py MCHC
python make3Dplot.py MCH
python make3Dplot.py MCV
python make3Dplot.py MEAN_RETIC_VOL
python make3Dplot.py MONO_COUNT
python make3Dplot.py MPV
python make3Dplot.py NEUTRO_COUNT
python make3Dplot.py PLT_COUNT
python make3Dplot.py RBC_COUNT
python make3Dplot.py RETIC_COUNT
python make3Dplot.py WBC_COUNT