python make3Dplot.py smooth BASO_COUNT
python make3Dplot.py smooth EO_COUNT
python make3Dplot.py smooth HCT
python make3Dplot.py smooth HGB
python make3Dplot.py smooth LYMPH_COUNT
python make3Dplot.py smooth MCHC
python make3Dplot.py smooth MCH
python make3Dplot.py smooth MCV
python make3Dplot.py smooth MEAN_RETIC_VOL
python make3Dplot.py smooth MONO_COUNT
python make3Dplot.py smooth MPV
python make3Dplot.py smooth NEUTRO_COUNT
python make3Dplot.py smooth PLT_COUNT
python make3Dplot.py smooth RBC_COUNT
python make3Dplot.py smooth RETIC_COUNT
python make3Dplot.py smooth WBC_COUNT

python make3Dplot.py raw BASO_COUNT
python make3Dplot.py raw EO_COUNT
python make3Dplot.py raw HCT
python make3Dplot.py raw HGB
python make3Dplot.py raw LYMPH_COUNT
python make3Dplot.py raw MCHC
python make3Dplot.py raw MCH
python make3Dplot.py raw MCV
python make3Dplot.py raw MEAN_RETIC_VOL
python make3Dplot.py raw MONO_COUNT
python make3Dplot.py raw MPV
python make3Dplot.py raw NEUTRO_COUNT
python make3Dplot.py raw PLT_COUNT
python make3Dplot.py raw RBC_COUNT
python make3Dplot.py raw RETIC_COUNT
python make3Dplot.py raw WBC_COUNT
